### ISSUE TITLE
Integrate into libratbag

### ISSUE THREAD

**Issue by zoeleu** [dokutan/mouse_m908#32]
https://github.com/libratbag/libratbag is the backend for Piper, the GTK gaming mouse GUI. Integrating in libratbag will allow for Redragon mouse support in Piper.

**Comment by jbalme** [comment]
Simplest way to do this in light of the licensing issues and language difference would be to make this project available as a library with an `extern "C"` interface, and have libratbag call it, either through a compile time dependency or through dlopen.

The correct way long term would be to standardize libratbag's D-BUS API, and allow multiple simultaneous implementations, like how MPRIS can be used to control multiple media players. Then Piper can provide a single interface to all peripherals to the users.

**Comment by dokutan** [comment]
@jbalme Your suggestions are good, creating a library to interact with Redragon mice would be potentially useful for other projects as well. If you (or someone else) are interested in doing this, go ahead. I am open to pull requests and questions, however i will not start work on this myself for a lack of time and personal interest.
I originally wrote mouse_m908 to control my own M908 (as the name suggests) and it served that purpose to my satisfaction. Additionally i am currently not using that mouse, so i have zero need for any changes to the interface.
