### ISSUE TITLE
Could this be made to work in WSL on Windows? I'd like to be able to....

### ISSUE THREAD

**Issue by JadianRadiator** [dokutan/mouse_m908#38]
Could this be made to work in WSL on Windows?
I'd like to be able to bring the ability to hand-write macros with me if & when I switch back to Windows.

**Comment by dokutan** [comment]
The only potential problem i can think of is that accessing usb devices using libusb might not work. I suggest that you simply try it out, feel free to report your results here. Please keep in mind that i can't give support for WSL.
