### ISSUE TITLE
Macro problems with M908 Ubuntu

### ISSUE THREAD

**Issue by riverrun-git** [dokutan/mouse_m908#40]
Running `mouse_m908 -R - ` shows this at the end:
```# Macros

;## macro1
;# down	m
;# up	m
;# down	a
;# up	a
;# delay	1
;# down	c
;# up	c
;# down	r
;# up	r
;# delay	1
;# down	o
;# up	o
;# down	1
;# up	1
;# delay	1
;# delay	1

;## macro8
;# unknown, please report as bug: ff ff 0
```

Sending a configuration file to the mouse works, but macros are ignored.
Tested on two different machines with Ubuntu 20.04 and 21.10 respectively.

**Comment by dokutan** [comment]
```
;## macro8
;# unknown, please report as bug: ff ff 0
```
This is a problem with reading the macros that i have personally seen before but haven't looked into yet. 

Attaching your whole config would be helpful for troubleshooting. To rule out a first cause, did you send the macros using the ``-m`` option?

```
mouse_m908 -c your_config.ini # this does not send the macros
mouse_m908 -m your_config.ini # this sends only the macros
```

**Comment by riverrun-git** [comment]
Ah. Didn't realize. Sending with '-m' did do the trick.
The error message when reading the config went away after I used the Windows software to create and assign a dozen macros to one of the profiles.
Cheeky question off-topic: any idea how to use the MacOS command key in a macro? Then I could use this mouse multi-platform...

Issue can be closed I assume.

**Comment by dokutan** [comment]
> Cheeky question off-topic: any idea how to use the MacOS command key in a macro? Then I could use this mouse multi-platform...

I don't know what the USB scan code for the command key is, but chances are high that it already exists under a different name in the [source code](https://github.com/dokutan/mouse_m908/blob/4492fd28c052222bc87072f20189f99cc1e78b44/include/data.cpp#L97). I recommend you try the following keys:
```
	{ "Ctrl_l", 0xe0 },
	{ "Alt_l", 0xe2 },
	{ "Super_l", 0xe3 },
	{ "Super_r", 0xe7 },
	{ "Alt_r", 0xe6 },
	{ "Ctrl_r", 0xe4 },
```
