### ISSUE TITLE
Supported Device:  UTech Venus Wireless Gaming Mouse

### ISSUE THREAD

**Issue by carakesa** [dokutan/mouse_m908#41]
Looks like this mouse is supported and is a clone of the RedDragon M913.

UtechSmart Venus Pro RGB Wireless MMO Gaming Mouse:

https://www.amazon.com/UtechSmart-transmission-technology-Ergonomic-programmable/dp/B07XP4K152?th=1

lsusb output:

`Bus 001 Device 007: ID 25a7:fa08 Areson Technology Corp 2.4G Dual Mode Mouse`

I've only messed with the dpi settings thus far, so I'm not sure if it's identical, but I don't see why it wouldn't be at this point.

sudo mouse_m908 --read -

```
# Model: 913
# Configuration created with mouse_m908 -R.
# This configuration can be send to the mouse with mouse_m908 -c.
# Note: this feature is incomplete for the M913.

# Battery level: 100 %

# The M913 has two profiles that can be switched using the 'mode switch' button on the bottom of the mouse.
# Reading the settings can only be done for the active profile, therefore only profile1 is used in this config.
[profile1]

report_rate=1000

# DPI settings
# Currently active DPI level: 2
dpi1=1000
dpi2=1500
dpi3=2000
dpi4=8000
dpi5=16000

# Button mapping
button_left=left
button_right=right
button_middle=middle
button_fire=unknown, please report as bug:  4  14  3  3a
button_1=keyboard_key
button_2=keyboard_key
button_3=keyboard_key
button_4=keyboard_key
button_5=keyboard_key
button_6=keyboard_key
button_7=keyboard_key
button_8=keyboard_key
button_9=keyboard_key
button_10=keyboard_key
button_11=keyboard_key
button_12=keyboard_key
```

**Comment by dokutan** [comment]
Thanks for the info, i have added it to the README.

I am closing this issue, for further discussion about improving the support for this mouse, see #15.
