### ISSUE TITLE
Support Confirmation: Pusat V8

### ISSUE THREAD

**Issue by ermangunal** [dokutan/mouse_m908#48]
Hello,
I have [Pusat V8](https://www.monsternotebook.com.tr/oyuncu-mouse/pusat-v8/) mice which is identical to Redragon M908. So I tried the driver of M908 on my mice on Fedora 37 and it is fully working.

It took me a while finding this driver. I hope next person who search it will be lucky :). Let me leave some tags here.

Pusat V8 open source driver. Pusat V8 açık kaynak sürücüsü.

Thanks for you great work!

**Comment by dokutan** [comment]
Thanks for opening this issue, i have added the Pusat V8 to the list of supported mice in the README.
