### ISSUE TITLE
Possible to assign other mouse functions to m908?

### ISSUE THREAD

**Issue by amper5and** [dokutan/mouse_m908#49]
I would like to assign mouse right/left tilt click function to a key on the m908 (tilt click is when the scroll wheel tilts to the right/left on some mice and actually registers a click - usually for scrolling horizontally). The m908 doesn't actually have native tilt click functionality but is it possible to use this to program the m908 to send a tilt click when pressing a key?

**Comment by dokutan** [comment]
> is it possible to use this to program the m908 to send a tilt click when pressing a key?

Unfortunately not, as the functionality is limited by the firmware.

I suggest mapping the keys to some unused keyboard keys (e.g. F13-F24 or some media controls) on the mouse, then using any of the uinput based tools to remap those to your desired events in userspace.

**Comment by amper5and** [comment]
That's what I suspected. Thank you for the reply and for this project.
