### ISSUE TITLE
AUR package doesn't compile

### ISSUE THREAD

**Issue by Leopard1907** [dokutan/mouse_m908#53]
```
include/rd_mouse_wireless.cpp:20:1: bilgi: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   19 | #include "rd_mouse_wireless.h"
  +++ |+#include <cstdint>
   20 | 
```

I assume this is due to release in AUR missing this.

https://github.com/dokutan/mouse_m908/commit/ddd86e88de73d10e1f410a2face932851c2178a4

https://aur.archlinux.org/packages/mouse_m908

**Comment by dokutan** [comment]
Thank you for reprting this problem. I have made a new release (3.4) that includes the relevant commit. At least for me, building from the AUR works, please reopen this issue if you encounter any problems.
