### ISSUE TITLE
M902 Samsara support

### ISSUE THREAD

**Issue by Cqoicebordel** [dokutan/mouse_m908#72]
First of all, thanks for all your work.  
Second, I know my mouse won't get any support. I'm just giving you this as a FYI.

So, lsusb : 
`Bus 005 Device 002: ID 04d9:fc01 Holtek Semiconductor, Inc. USB Laser Game Mouse`

I edited `data.cpp` to insert  
`	0xfc01, // M902 Samsara`  
at line 32.

Then, ran `sudo ./mouse_m908 -D dump-output.txt` and `sudo ./mouse_m908 -R read-output.txt` :  
[dump-output.txt](https://github.com/user-attachments/files/15566238/dump-output.txt)
[read-output.txt](https://github.com/user-attachments/files/15566241/read-output.txt)

I can see clearly it's a mess, and nothing can be extracted from this. I never succeeded to use passthrough with a VM, so I can't get further than this.

But at least, now, there is a bug open for that model, and you can add its status as "not supported" in the readme :)

**Comment by dokutan** [comment]
Thanks for opening this issue, i have added this mouse to the list in the README.

If you (or someone else) manages to get this mouse working, i would of course welcome a PR, however i will close this issue until then.
