### ISSUE TITLE
macro questions

### ISSUE THREAD

**Issue by 40476** [dokutan/mouse_m908#73]
I have a few questions,
1. how to create an auto repeating macro?
2. how to do keyboard shortcuts
3. how to do keys such as F13 and F24
4. how to type a string, and press a keyboard key, enter a shortcut , and start typing again all in one macro?
5. when will we be getting a way to convert the mouse utilities `.pwd` files to the supported .ini format?

**Comment by dokutan** [comment]
1. how to create an auto repeating macro?
With macro<…>:<…>, see https://github.com/dokutan/mouse_m908/blob/master/keymap.md#macros-see-readmemd
2. how to do keyboard shortcuts
By specifying each key up/down event individually, i.e.:
```
down	Ctrl_l
down	a
up	a
up	Ctrl_l
```
3. how to do keys such as F13 and F24
With F13 - F24, see https://github.com/dokutan/mouse_m908/blob/master/keymap.md#keyboard-keys.
4. how to type a string, and press a keyboard key, enter a shortcut , and start typing again all in one macro?
By specifying each key up/down event individually
5. when will we be getting a way to convert the mouse utilities `.pwd` files to the supported .ini format?
When someone implements it and opens a pull request.
