### ISSUE TITLE
Button mapping syntax and problem

### ISSUE THREAD

**Issue by atmafox** [dokutan/mouse_m908#9]
```
button_11=-
button_12==
```

The above code does not function correctly, the result is button 11 returns nothing and button 12 returns -.

**Comment by dokutan** [comment]
It should be:
```
button_11=Minus
button_12=Equals
```
[here](https://github.com/dokutan/mouse_m908/blob/master/keymap.md#keys) is a list of valid key names. If that doesn't work for you, could you please post the output of ``mouse_m908 -R -`` and ``mouse_m908 -D -``?

**Comment by atmafox** [comment]
Thank you!  That did the trick!
